// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Entry struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Content   pgtype.Text        `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	FolderID  int64              `json:"folder_id"`
}

type EntryTag struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	EntryID   int64              `json:"entry_id"`
	TagID     int64              `json:"tag_id"`
}

type Folder struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ParentFolderID pgtype.Int8        `json:"parent_folder_id"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiredAt pgtype.Timestamptz `json:"expired_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserFolder struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    int64              `json:"user_id"`
	FolderID  int64              `json:"folder_id"`
}
