// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	AssignFolderToUser(ctx context.Context, arg AssignFolderToUserParams) (UserFolder, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindEntryById(ctx context.Context, id int64) (Entry, error)
	FindFolderById(ctx context.Context, id int64) (Folder, error)
	FindUserById(ctx context.Context, id int64) (User, error)
	ListEntriesByFolderId(ctx context.Context, folderID int64) ([]Entry, error)
	ListFoldersByUserId(ctx context.Context, userID int64) ([]ListFoldersByUserIdRow, error)
}

var _ Querier = (*Queries)(nil)
