// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	AssignFolderToUser(ctx context.Context, arg AssignFolderToUserParams) (UserFolder, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSessionByToken(ctx context.Context, token string) error
	DeleteSessionsByIds(ctx context.Context, dollar_1 []int64) error
	FindActiveSessionByToken(ctx context.Context, token string) (Session, error)
	FindEntryById(ctx context.Context, id int64) (Entry, error)
	FindFolderById(ctx context.Context, id int64) (Folder, error)
	FindSessionByToken(ctx context.Context, token string) (Session, error)
	FindSessionsByUserId(ctx context.Context, userID int64) ([]Session, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserById(ctx context.Context, id int64) (User, error)
	FindUsersIdsByFolderId(ctx context.Context, folderID int64) ([]UserFolder, error)
	ListEntriesByFolderId(ctx context.Context, folderID int64) ([]Entry, error)
	ListFoldersByUserId(ctx context.Context, userID int64) ([]ListFoldersByUserIdRow, error)
}

var _ Querier = (*Queries)(nil)
