// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignFolderToUser = `-- name: AssignFolderToUser :one
INSERT INTO user_folders (user_id, folder_id)
VALUES ($1, $2)
RETURNING id, created_at, user_id, folder_id
`

type AssignFolderToUserParams struct {
	UserID   int64 `json:"user_id"`
	FolderID int64 `json:"folder_id"`
}

func (q *Queries) AssignFolderToUser(ctx context.Context, arg AssignFolderToUserParams) (UserFolder, error) {
	row := q.db.QueryRow(ctx, assignFolderToUser, arg.UserID, arg.FolderID)
	var i UserFolder
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.FolderID,
	)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (name, content, folder_id)
VALUES ($1, $2, $3)
RETURNING id, name, content, created_at, updated_at, folder_id
`

type CreateEntryParams struct {
	Name     string      `json:"name"`
	Content  pgtype.Text `json:"content"`
	FolderID int64       `json:"folder_id"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry, arg.Name, arg.Content, arg.FolderID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FolderID,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (name, description, parent_folder_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_at, updated_at, parent_folder_id
`

type CreateFolderParams struct {
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	ParentFolderID pgtype.Int8 `json:"parent_folder_id"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.Name, arg.Description, arg.ParentFolderID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentFolderID,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, user_id)
VALUES ($1, $2)
RETURNING id, user_id, token, expiration, created_at
`

type CreateRefreshTokenParams struct {
	Token  string `json:"token"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Expiration,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password)
VALUES ($1, $2)
RETURNING id, email, password, created_at
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshTokensByIds = `-- name: DeleteRefreshTokensByIds :exec
DELETE FROM refresh_tokens
WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteRefreshTokensByIds(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByIds, dollar_1)
	return err
}

const findEntryById = `-- name: FindEntryById :one
SELECT id, name, content, created_at, updated_at, folder_id FROM entries WHERE entries.id = $1
`

func (q *Queries) FindEntryById(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRow(ctx, findEntryById, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FolderID,
	)
	return i, err
}

const findFolderById = `-- name: FindFolderById :one
SELECT id, name, description, created_at, updated_at, parent_folder_id FROM folders WHERE id = $1
`

func (q *Queries) FindFolderById(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRow(ctx, findFolderById, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentFolderID,
	)
	return i, err
}

const findRefreshTokenByToken = `-- name: FindRefreshTokenByToken :one
SELECT id, user_id, token, expiration, created_at
FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) FindRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshTokenByToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Expiration,
		&i.CreatedAt,
	)
	return i, err
}

const findRefreshTokensByUserId = `-- name: FindRefreshTokensByUserId :many
SELECT id, user_id, token, expiration, created_at
FROM refresh_tokens
WHERE user_id = $1
ORDER BY expiration ASC
`

func (q *Queries) FindRefreshTokensByUserId(ctx context.Context, userID int64) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, findRefreshTokensByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Expiration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, password, created_at
FROM users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT id, email, password, created_at
FROM users
WHERE users.id = $1
`

func (q *Queries) FindUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const listEntriesByFolderId = `-- name: ListEntriesByFolderId :many
SELECT id, name, content, created_at, updated_at, folder_id 
FROM entries
WHERE entries.folder_id = $1
ORDER BY name
`

func (q *Queries) ListEntriesByFolderId(ctx context.Context, folderID int64) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByFolderId, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FolderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByUserId = `-- name: ListFoldersByUserId :many
SELECT folders.id, name, description, folders.created_at, updated_at, parent_folder_id, user_folders.id, user_folders.created_at, user_id, folder_id 
FROM folders INNER JOIN user_folders on folders.id = user_folders.folder_id
WHERE user_folders.user_id = $1
ORDER BY name
`

type ListFoldersByUserIdRow struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ParentFolderID pgtype.Int8        `json:"parent_folder_id"`
	ID_2           int64              `json:"id_2"`
	CreatedAt_2    pgtype.Timestamptz `json:"created_at_2"`
	UserID         int64              `json:"user_id"`
	FolderID       int64              `json:"folder_id"`
}

func (q *Queries) ListFoldersByUserId(ctx context.Context, userID int64) ([]ListFoldersByUserIdRow, error) {
	rows, err := q.db.Query(ctx, listFoldersByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFoldersByUserIdRow
	for rows.Next() {
		var i ListFoldersByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentFolderID,
			&i.ID_2,
			&i.CreatedAt_2,
			&i.UserID,
			&i.FolderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRefreshToken = `-- name: UpdateRefreshToken :one
UPDATE refresh_tokens
SET token = $1,
    expiration = $2
WHERE id = $3
RETURNING id, user_id, token, expiration, created_at
`

type UpdateRefreshTokenParams struct {
	Token      string             `json:"token"`
	Expiration pgtype.Timestamptz `json:"expiration"`
	ID         int64              `json:"id"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, updateRefreshToken, arg.Token, arg.Expiration, arg.ID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Expiration,
		&i.CreatedAt,
	)
	return i, err
}
