// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	AssignFolderToUser(ctx context.Context, arg AssignFolderToUserParams) (UserFolder, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRefreshTokensByIds(ctx context.Context, dollar_1 []int64) error
	FindEntryById(ctx context.Context, id int64) (Entry, error)
	FindFolderById(ctx context.Context, id int64) (Folder, error)
	FindRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error)
	FindRefreshTokensByUserId(ctx context.Context, userID int64) ([]RefreshToken, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserById(ctx context.Context, id int64) (User, error)
	ListEntriesByFolderId(ctx context.Context, folderID int64) ([]Entry, error)
	ListFoldersByUserId(ctx context.Context, userID int64) ([]ListFoldersByUserIdRow, error)
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (RefreshToken, error)
}

var _ Querier = (*Queries)(nil)
